### ISSUE TITLE
Error in Xcode when building for iOS

### ISSUE THREAD

**Issue by tippington** [DopamineLabs/DopamineKit-Unity#3]
Unity project builds fine, but when attempting to build the resulting Xcode project for Simulator or Device, the build fails with the following message:

> FileNotFoundException: Could not find file "/var/mobile/Containers/Data/Application/4DA40860-75A2-41AD-AD54-C299B14BE5AA/Documents/dopamineproperties.xml"

**Comment by cuddergambino** [comment]
The bug is fixed now. #4
Instead of using dopamineproperties.xml, you now just need to put your credentials in DopamineCredentials.cs (API dev and private keys, appID, and versionID).
The DopamineKit files are stored in the [Assets folder](https://github.com/DopamineLabs/DopamineKit-Unity/tree/master/Assets/DopamineKit)
